# -*- coding: utf-8 -*-
"""AI_Trading_Bot_ULTRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ueNAiOEhnZFK4amuq2MfL9M3NVdsL5C

# 🤖 AI Trading Signal Bot — ULTRA PRO
### XM Markets Edition | Multi-Timeframe Analysis | Self-Improving ML

```
Symbols  : GOLD, BTC, USDJPY, EURUSD, US100, ETH, JP225, GBPUSD, SILVER, GBPJPY, OIL
Timeframe: MTF (15m + 1h + 4h confluence)
ML Model : RandomForest + GradientBoosting + Voting Ensemble
Accuracy : Multi-factor confluence + Regime filter + News sentiment
Deploy   : Google Colab (free) with keep-alive
```
---
"""

# ================== INSTALL ==================
# !pip install yfinance pandas ta scikit-learn matplotlib seaborn numpy scipy requests --quiet
print('✅ All packages installed')

# ================== IMPORTS ==================
import os, time, smtplib, warnings, json, requests
import numpy as np
import pandas as pd
import yfinance as yf
import ta
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyArrowPatch
from email.mime.multipart import MIMEMultipart
from email.mime.text  import MIMEText
from email.mime.image import MIMEImage
from scipy.stats      import linregress, pearsonr
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics         import accuracy_score, precision_score
from collections import defaultdict
from datetime import datetime

warnings.filterwarnings('ignore')
pd.set_option('display.float_format', '{:.5f}'.format)
print('✅ Imports ready')

# ================== CONFIG ==================
import getpass

EMAIL        = os.environ.get('TRADING_EMAIL', 'your_email@gmail.com')
APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')
if not APP_PASSWORD:
    APP_PASSWORD = getpass.getpass('🔑 Gmail App Password: ')

# ─── XM Market Symbols (จากภาพ + เพิ่มเติม) ───────────────────────────
SYMBOLS = {
    # Forex
    'EURUSD':  'EURUSD=X',
    'USDJPY':  'USDJPY=X',
    'GBPUSD':  'GBPUSD=X',
    'GBPJPY':  'GBPJPY=X',
    'AUDUSD':  'AUDUSD=X',
    'USDCHF':  'USDCHF=X',
    'USDCAD':  'USDCAD=X',
    # Crypto
    'BTCUSD':  'BTC-USD',
    'ETHUSD':  'ETH-USD',
    'SOLUSD':  'SOL-USD',
    # Commodities
    'GOLD':    'GC=F',
    'SILVER':  'SI=F',
    'OIL':     'CL=F',
    # Indices
    'US100':   'NQ=F',
    'US30':    'YM=F',
    'JP225':   '^N225',
    'GER40':   '^GDAXI',
}

# ─── Multi-Timeframe Config ────────────────────────────────────────────
MTF_CONFIG = {
    'fast':   {'interval': '15m',  'period': '7d',   'weight': 0.25},  # entry timing
    'medium': {'interval': '1h',   'period': '30d',  'weight': 0.45},  # main signal
    'slow':   {'interval': '4h',   'period': '60d',  'weight': 0.30},  # trend filter
}

# ─── Risk Parameters ──────────────────────────────────────────────────
ATR_SL_MULT  = 1.8   # SL = ATR x นี้
ATR_TP_MULT  = 3.2   # TP = ATR x นี้  → R:R ≈ 1:1.78
MIN_CONF     = 0.62  # ขั้นต่ำส่ง signal
TOP_N        = 3     # ส่ง top N symbols
MIN_ADX      = 20    # กรอง sideways (ADX < 20 = skip)
MIN_RR       = 1.5   # กรอง R:R ต่ำ

# ─── Self-Learning Storage ────────────────────────────────────────────
TRADE_LOG_FILE = 'trade_log.json'   # เก็บ history สำหรับ self-improve

print(f'✅ Config ready | {len(SYMBOLS)} symbols | MTF: {list(MTF_CONFIG.keys())}')

# ================== DATA FETCHER ==================
def fetch_data(yf_symbol, interval='1h', period='30d'):
    df = yf.download(yf_symbol, period=period, interval=interval,
                     progress=False, auto_adjust=True)
    if df.empty:
        raise ValueError(f'No data for {yf_symbol}')
    df.columns = df.columns.get_level_values(0)
    for col in ['Open','High','Low','Close','Volume']:
        if col in df.columns:
            df[col] = df[col].squeeze()
    df.dropna(inplace=True)
    return df


def fetch_mtf(yf_symbol):
    """ดึงข้อมูล 3 timeframe พร้อมกัน"""
    data = {}
    for tf_name, cfg in MTF_CONFIG.items():
        try:
            data[tf_name] = fetch_data(yf_symbol, cfg['interval'], cfg['period'])
        except Exception as e:
            print(f'    ⚠️ {tf_name} fetch failed: {e}')
            data[tf_name] = None
    return data

print('✅ Data fetcher ready')

# ================== INDICATORS (FULL SUITE) ==================
def compute_indicators(df):
    c = df['Close']
    h = df['High']
    l = df['Low']
    v = df.get('Volume', pd.Series(np.ones(len(df)), index=df.index))
    if hasattr(v, 'squeeze'): v = v.squeeze()

    # ── TREND ─────────────────────────────────────────────────────────
    for w in [9, 20, 50, 100, 200]:
        df[f'EMA{w}'] = ta.trend.ema_indicator(c, window=w)
    df['SMA20']  = ta.trend.sma_indicator(c, window=20)
    df['SMA200'] = ta.trend.sma_indicator(c, window=200)

    adx = ta.trend.ADXIndicator(h, l, c, window=14)
    df['ADX']     = adx.adx()
    df['ADX_pos'] = adx.adx_pos()
    df['ADX_neg'] = adx.adx_neg()

    macd = ta.trend.MACD(c)
    df['MACD']        = macd.macd()
    df['MACD_signal'] = macd.macd_signal()
    df['MACD_hist']   = macd.macd_diff()

    # Ichimoku
    ichi = ta.trend.IchimokuIndicator(h, l)
    df['ICHI_conv']   = ichi.ichimoku_conversion_line()
    df['ICHI_base']   = ichi.ichimoku_base_line()
    df['ICHI_span_a'] = ichi.ichimoku_a()
    df['ICHI_span_b'] = ichi.ichimoku_b()

    # Parabolic SAR
    df['PSAR']    = ta.trend.PSARIndicator(h, l, c).psar()
    df['PSAR_bull']= ta.trend.PSARIndicator(h, l, c).psar_up_indicator()
    df['PSAR_bear']= ta.trend.PSARIndicator(h, l, c).psar_down_indicator()

    # ── MOMENTUM ──────────────────────────────────────────────────────
    df['RSI']      = ta.momentum.rsi(c, window=14)
    df['RSI7']     = ta.momentum.rsi(c, window=7)
    df['RSI21']    = ta.momentum.rsi(c, window=21)

    stoch = ta.momentum.StochasticOscillator(h, l, c)
    df['STOCH_k']  = stoch.stoch()
    df['STOCH_d']  = stoch.stoch_signal()

    df['ROC10']    = ta.momentum.roc(c, window=10)
    df['ROC20']    = ta.momentum.roc(c, window=20)
    df['WILLR']    = ta.momentum.williams_r(h, l, c)
    df['CCI']      = ta.trend.CCIIndicator(h, l, c).cci()
    df['TSI']      = ta.momentum.TSIIndicator(c).tsi()  # True Strength Index

    # ── VOLATILITY ────────────────────────────────────────────────────
    for w, dev in [(20,2), (20,1), (20,3)]:
        bb = ta.volatility.BollingerBands(c, window=w, window_dev=dev)
        suffix = '' if dev == 2 else f'_{dev}'
        df[f'BB_high{suffix}'] = bb.bollinger_hband()
        df[f'BB_low{suffix}']  = bb.bollinger_lband()
    df['BB_mid']   = ta.volatility.BollingerBands(c).bollinger_mavg()
    df['BB_width'] = (df['BB_high'] - df['BB_low']) / df['BB_mid']
    df['BB_pct']   = ta.volatility.BollingerBands(c).bollinger_pband()

    atr = ta.volatility.AverageTrueRange(h, l, c, window=14)
    df['ATR']      = atr.average_true_range()
    df['ATR_pct']  = df['ATR'] / c * 100

    kc = ta.volatility.KeltnerChannel(h, l, c)
    df['KC_high']  = kc.keltner_channel_hband()
    df['KC_low']   = kc.keltner_channel_lband()
    df['SQUEEZE']  = (df['BB_high'] < df['KC_high']) & (df['BB_low'] > df['KC_low'])

    # Donchian Channel (breakout)
    df['DC_high']  = h.rolling(20).max()
    df['DC_low']   = l.rolling(20).min()

    # ── VOLUME ────────────────────────────────────────────────────────
    v_safe = v.replace(0, np.nan).fillna(1)
    df['OBV']      = ta.volume.on_balance_volume(c, v)
    df['CMF']      = ta.volume.chaikin_money_flow(h, l, c, v)
    df['MFI']      = ta.volume.money_flow_index(h, l, c, v)
    df['VWAP']     = (((h + l + c) / 3) * v).cumsum() / v.cumsum()
    df['VOL_MA']   = v.rolling(20).mean()
    df['VOL_RATIO']= v / df['VOL_MA'].replace(0, np.nan)
    df['AD']       = ta.volume.acc_dist_index(h, l, c, v)  # Accumulation/Distribution

    # ── FIBONACCI ─────────────────────────────────────────────────────
    n = min(55, len(df))
    hi = df['High'].rolling(n).max()
    lo = df['Low'].rolling(n).min()
    rng = hi - lo
    for lvl, pct in [('236', 0.236), ('382', 0.382), ('500', 0.500),
                     ('618', 0.618), ('786', 0.786)]:
        df[f'FIB_{lvl}'] = hi - pct * rng

    # ── MARKET REGIME ─────────────────────────────────────────────────
    # Hurst Exponent (>0.5 = trending, <0.5 = mean-reverting)
    def hurst_exp(ts, max_lag=20):
        if len(ts) < max_lag * 2:
            return 0.5
        lags = range(2, max_lag)
        tau = []
        for lag in lags:
            diff = ts[lag:] - ts[:-lag]
            tau.append(np.sqrt(np.std(diff)))
        try:
            slope, *_ = linregress(np.log(list(lags)), np.log(tau))
            return slope * 2.0
        except:
            return 0.5

    df['HURST'] = c.rolling(40).apply(
        lambda x: hurst_exp(x.values), raw=False)

    # Linear Regression Slope (normalized)
    def lr_slope_norm(series, n=20):
        slopes = [np.nan] * n
        for i in range(n, len(series)):
            y = series.iloc[i-n:i].values
            x = np.arange(n)
            slope, *_ = linregress(x, y)
            slopes.append(slope / (y.mean() + 1e-10) * 100)  # normalize
        return pd.Series(slopes, index=series.index)

    df['LR_SLOPE'] = lr_slope_norm(c)

    # Volatility Regime (low/normal/high)
    atr_ma = df['ATR'].rolling(50).mean()
    df['VOL_REGIME'] = np.where(df['ATR'] > atr_ma * 1.3, 2,
                        np.where(df['ATR'] < atr_ma * 0.7, 0, 1))

    df.dropna(inplace=True)
    return df

print('✅ Indicator suite ready')

# ================== MULTI-TIMEFRAME ANALYSIS ==================
def mtf_bias(mtf_data):
    """
    วิเคราะห์ทิศทาง (bias) ของแต่ละ timeframe
    Return: dict {tf: ('BUY'|'SELL'|'NEUTRAL', strength 0-1)}
    """
    result = {}

    for tf_name, df in mtf_data.items():
        if df is None or len(df) < 50:
            result[tf_name] = ('NEUTRAL', 0.5)
            continue
        try:
            df = compute_indicators(df)
            last = df.iloc[-1]
            buy_pts = sell_pts = 0

            # 1. EMA trend
            if last['EMA9'] > last['EMA20'] > last['EMA50']:
                buy_pts += 2
            elif last['EMA9'] < last['EMA20'] < last['EMA50']:
                sell_pts += 2

            # 2. Price vs EMA200 (macro trend)
            if last['Close'] > last['EMA200']:
                buy_pts += 1
            else:
                sell_pts += 1

            # 3. ADX direction
            if last['ADX'] > MIN_ADX:
                if last['ADX_pos'] > last['ADX_neg']:
                    buy_pts += 1
                else:
                    sell_pts += 1

            # 4. MACD
            if last['MACD'] > last['MACD_signal'] and last['MACD_hist'] > 0:
                buy_pts += 1
            elif last['MACD'] < last['MACD_signal'] and last['MACD_hist'] < 0:
                sell_pts += 1

            # 5. Ichimoku cloud
            cloud_top = max(last['ICHI_span_a'], last['ICHI_span_b'])
            cloud_bot = min(last['ICHI_span_a'], last['ICHI_span_b'])
            if last['Close'] > cloud_top:
                buy_pts += 1
            elif last['Close'] < cloud_bot:
                sell_pts += 1

            # 6. Hurst (trending regime)
            if last['HURST'] > 0.55:
                if buy_pts > sell_pts:
                    buy_pts += 0.5
                else:
                    sell_pts += 0.5

            total = buy_pts + sell_pts
            if total == 0:
                result[tf_name] = ('NEUTRAL', 0.5)
                continue

            bias    = 'BUY' if buy_pts >= sell_pts else 'SELL'
            strength = max(buy_pts, sell_pts) / total
            result[tf_name] = (bias, strength, df)

        except Exception as e:
            result[tf_name] = ('NEUTRAL', 0.5)

    return result


def mtf_confluence_score(mtf_biases):
    """
    คำนวณ confluence: ทุก TF เห็นด้วยหรือไม่
    Return: (signal, confluence_score 0-1, alignment_count)
    """
    weighted_buy = weighted_sell = 0
    aligned = 0

    for tf_name, cfg in MTF_CONFIG.items():
        if tf_name not in mtf_biases:
            continue
        bias_info = mtf_biases[tf_name]
        bias      = bias_info[0]
        strength  = bias_info[1]
        w         = cfg['weight']

        if bias == 'BUY':
            weighted_buy  += w * strength
        elif bias == 'SELL':
            weighted_sell += w * strength

    signal = 'BUY' if weighted_buy >= weighted_sell else 'SELL'
    total  = weighted_buy + weighted_sell
    confluence = max(weighted_buy, weighted_sell) / total if total > 0 else 0.5

    # bonus: slow TF เห็นด้วยกับ medium
    slow_bias   = mtf_biases.get('slow',   ('NEUTRAL',))[0]
    medium_bias = mtf_biases.get('medium', ('NEUTRAL',))[0]
    fast_bias   = mtf_biases.get('fast',   ('NEUTRAL',))[0]

    alignment = sum([
        slow_bias   == signal,
        medium_bias == signal,
        fast_bias   == signal,
    ])

    # เพิ่ม confidence ถ้า alignment สูง
    confluence_bonus = (alignment - 1) * 0.05  # +5% per extra alignment
    confluence = min(1.0, confluence + confluence_bonus)

    return signal, confluence, alignment

print('✅ MTF analysis ready')

# ================== ML ENGINE (ENSEMBLE) ==================
def build_features(df):
    cols = [
        'RSI', 'RSI7', 'RSI21', 'MACD_hist', 'STOCH_k', 'STOCH_d',
        'BB_pct', 'BB_width', 'ATR_pct', 'ADX', 'ADX_pos', 'ADX_neg',
        'ROC10', 'ROC20', 'WILLR', 'CCI', 'TSI', 'CMF', 'MFI',
        'VOL_RATIO', 'LR_SLOPE', 'HURST', 'VOL_REGIME'
    ]
    return [c for c in cols if c in df.columns]


def train_ensemble(df):
    """
    Voting Ensemble: RF + GBM + Weighted vote
    Label: close[+5] > close * 1.005 → BUY (1)
    """
    df = df.copy()
    df['future'] = df['Close'].shift(-5)
    df['label']  = ((df['future'] / df['Close'] - 1) > 0.005).astype(int)
    df.dropna(inplace=True)

    feat_cols = build_features(df)
    X = df[feat_cols].values
    y = df['label'].values

    if len(X) < 80:
        return None, None, 0.5, 0.5, feat_cols

    tscv   = TimeSeriesSplit(n_splits=4)
    scaler = StandardScaler()

    rf  = RandomForestClassifier(n_estimators=150, max_depth=6,
                                  min_samples_leaf=5, random_state=42, n_jobs=-1)
    gbm = GradientBoostingClassifier(n_estimators=100, max_depth=4,
                                      learning_rate=0.05, random_state=42)
    ensemble = VotingClassifier([('rf', rf), ('gbm', gbm)], voting='soft')

    accs, precs = [], []
    for tr, te in tscv.split(X):
        Xtr = scaler.fit_transform(X[tr])
        Xte = scaler.transform(X[te])
        ensemble.fit(Xtr, y[tr])
        pred = ensemble.predict(Xte)
        accs.append(accuracy_score(y[te], pred))
        if pred.sum() > 0:
            precs.append(precision_score(y[te], pred, zero_division=0))

    avg_acc  = np.mean(accs)
    avg_prec = np.mean(precs) if precs else 0.5

    # Final fit
    X_scaled = scaler.fit_transform(X)
    ensemble.fit(X_scaled, y)

    return ensemble, scaler, avg_acc, avg_prec, feat_cols


def ml_prob(model, scaler, df, feat_cols):
    if model is None:
        return 0.5
    x = scaler.transform(df[feat_cols].iloc[-1:].values)
    return model.predict_proba(x)[0][1]

print('✅ ML ensemble ready')

# ================== SCORING ENGINE (UPGRADED) ==================
def rule_score(df):
    """
    Rule-based scoring: 20+ conditions, return (signal, ratio, buy, sell, reasons)
    """
    last  = df.iloc[-1]
    prev  = df.iloc[-2]
    prev2 = df.iloc[-3]
    buy_sc = sell_sc = 0
    rb = []   # reasons buy
    rs = []   # reasons sell

    def b(pts, reason): nonlocal buy_sc;  buy_sc  += pts; rb.append(reason)
    def s(pts, reason): nonlocal sell_sc; sell_sc += pts; rs.append(reason)

    # ── 1. EMA Structure ──────────────────────────────────────────────
    if last['EMA9'] > last['EMA20'] > last['EMA50'] > last['EMA100']:
        b(3, 'Full EMA bullish stack (9>20>50>100)')
    elif last['EMA9'] < last['EMA20'] < last['EMA50'] < last['EMA100']:
        s(3, 'Full EMA bearish stack (9<20<50<100)')
    elif last['EMA9'] > last['EMA20'] > last['EMA50']:
        b(2, 'EMA bullish stack (9>20>50)')
    elif last['EMA9'] < last['EMA20'] < last['EMA50']:
        s(2, 'EMA bearish stack (9<20<50)')

    # Golden/Death Cross (EMA20/EMA50)
    if prev['EMA20'] <= prev['EMA50'] and last['EMA20'] > last['EMA50']:
        b(2, 'Golden Cross EMA20/50')
    elif prev['EMA20'] >= prev['EMA50'] and last['EMA20'] < last['EMA50']:
        s(2, 'Death Cross EMA20/50')

    # ── 2. ADX Trend Strength ─────────────────────────────────────────
    adx = last['ADX']
    if adx > 30:
        if last['ADX_pos'] > last['ADX_neg']: b(2, f'ADX={adx:.0f} very strong uptrend')
        else:                                  s(2, f'ADX={adx:.0f} very strong downtrend')
    elif adx > MIN_ADX:
        if last['ADX_pos'] > last['ADX_neg']: b(1, f'ADX={adx:.0f} uptrend')
        else:                                  s(1, f'ADX={adx:.0f} downtrend')

    # ── 3. MACD ───────────────────────────────────────────────────────
    if prev['MACD'] < prev['MACD_signal'] and last['MACD'] > last['MACD_signal']:
        b(2, 'MACD bullish crossover')
    elif prev['MACD'] > prev['MACD_signal'] and last['MACD'] < last['MACD_signal']:
        s(2, 'MACD bearish crossover')
    if last['MACD_hist'] > 0 and last['MACD_hist'] > prev['MACD_hist'] > prev2['MACD_hist']:
        b(1, 'MACD histogram accelerating up')
    elif last['MACD_hist'] < 0 and last['MACD_hist'] < prev['MACD_hist'] < prev2['MACD_hist']:
        s(1, 'MACD histogram accelerating down')

    # ── 4. RSI (Divergence-aware) ──────────────────────────────────────
    rsi = last['RSI']
    if rsi < 25:    b(3, f'RSI deeply oversold ({rsi:.0f})')
    elif rsi < 35:  b(2, f'RSI oversold ({rsi:.0f})')
    elif rsi < 45:  b(1, f'RSI near oversold ({rsi:.0f})')
    elif rsi > 75:  s(3, f'RSI deeply overbought ({rsi:.0f})')
    elif rsi > 65:  s(2, f'RSI overbought ({rsi:.0f})')
    elif rsi > 55:  s(1, f'RSI near overbought ({rsi:.0f})')

    # RSI Momentum (fast > slow = bullish momentum)
    if last['RSI7'] > last['RSI21'] and prev['RSI7'] <= prev['RSI21']:
        b(1, 'RSI7 crossed above RSI21')
    elif last['RSI7'] < last['RSI21'] and prev['RSI7'] >= prev['RSI21']:
        s(1, 'RSI7 crossed below RSI21')

    # ── 5. Bollinger Bands ────────────────────────────────────────────
    bp = last['BB_pct']
    if last['Close'] < last['BB_low_1']:  b(2, 'Price below BB lower (1σ)')
    elif last['Close'] < last['BB_low']:  b(1, 'Price below BB lower (2σ)')
    if last['Close'] > last['BB_high_1']: s(2, 'Price above BB upper (1σ)')
    elif last['Close'] > last['BB_high']: s(1, 'Price above BB upper (2σ)')

    # BB Squeeze breakout
    if last['SQUEEZE'] and not prev['SQUEEZE']:
        if last['LR_SLOPE'] > 0: b(2, 'BB Squeeze release (bullish)')
        else:                     s(2, 'BB Squeeze release (bearish)')

    # Donchian breakout
    if last['Close'] >= last['DC_high']:  b(2, 'Donchian 20 high breakout')
    elif last['Close'] <= last['DC_low']: s(2, 'Donchian 20 low breakdown')

    # ── 6. Stochastic ─────────────────────────────────────────────────
    if last['STOCH_k'] < 20 and last['STOCH_k'] > last['STOCH_d']:
        b(2, f"Stoch bullish cross OS zone ({last['STOCH_k']:.0f})")
    elif last['STOCH_k'] < 20:
        b(1, f"Stoch oversold ({last['STOCH_k']:.0f})")
    if last['STOCH_k'] > 80 and last['STOCH_k'] < last['STOCH_d']:
        s(2, f"Stoch bearish cross OB zone ({last['STOCH_k']:.0f})")
    elif last['STOCH_k'] > 80:
        s(1, f"Stoch overbought ({last['STOCH_k']:.0f})")

    # ── 7. Ichimoku ───────────────────────────────────────────────────
    cloud_top = max(last['ICHI_span_a'], last['ICHI_span_b'])
    cloud_bot = min(last['ICHI_span_a'], last['ICHI_span_b'])
    if   last['Close'] > cloud_top: b(2, 'Above Ichimoku cloud')
    elif last['Close'] < cloud_bot: s(2, 'Below Ichimoku cloud')
    if prev['ICHI_conv'] <= prev['ICHI_base'] and last['ICHI_conv'] > last['ICHI_base']:
        b(2, 'Ichimoku TK bullish cross')
    elif prev['ICHI_conv'] >= prev['ICHI_base'] and last['ICHI_conv'] < last['ICHI_base']:
        s(2, 'Ichimoku TK bearish cross')

    # ── 8. Parabolic SAR ──────────────────────────────────────────────
    if last['PSAR_bull'] == 1:  b(1, 'PSAR bullish flip')
    elif last['PSAR_bear'] == 1: s(1, 'PSAR bearish flip')

    # ── 9. VWAP ───────────────────────────────────────────────────────
    if   last['Close'] > last['VWAP'] * 1.002: b(1, 'Price above VWAP')
    elif last['Close'] < last['VWAP'] * 0.998: s(1, 'Price below VWAP')

    # ── 10. Volume ────────────────────────────────────────────────────
    if last['VOL_RATIO'] > 1.8:
        if last['CMF'] > 0.1: b(2, f"Volume spike + CMF={last['CMF']:.2f}")
        elif last['CMF'] < -0.1: s(2, f"Volume spike + CMF={last['CMF']:.2f}")
    if last['MFI'] < 20: b(1, f"MFI oversold ({last['MFI']:.0f})")
    elif last['MFI'] > 80: s(1, f"MFI overbought ({last['MFI']:.0f})")

    # AD trend
    if last['AD'] > prev['AD'] > prev2['AD']:  b(1, 'A/D accumulation')
    elif last['AD'] < prev['AD'] < prev2['AD']: s(1, 'A/D distribution')

    # ── 11. TSI ───────────────────────────────────────────────────────
    if   last['TSI'] > 0 and prev['TSI'] <= 0: b(1, 'TSI crossed above 0')
    elif last['TSI'] < 0 and prev['TSI'] >= 0: s(1, 'TSI crossed below 0')

    # ── 12. CCI + Williams %R ─────────────────────────────────────────
    if last['CCI'] < -150:   b(1, f"CCI deep oversold ({last['CCI']:.0f})")
    elif last['CCI'] > 150:  s(1, f"CCI deep overbought ({last['CCI']:.0f})")
    if last['WILLR'] < -90:  b(1, f"Williams %R oversold ({last['WILLR']:.0f})")
    elif last['WILLR'] > -10: s(1, f"Williams %R overbought ({last['WILLR']:.0f})")

    # ── 13. Fibonacci ─────────────────────────────────────────────────
    for lvl in ['618', '500', '382']:
        key = f'FIB_{lvl}'
        if abs(last['Close'] - last[key]) / last['Close'] < 0.003:
            if buy_sc > sell_sc: b(1, f'Near Fib {lvl}')
            else:                 s(1, f'Near Fib {lvl}')
            break

    # ── 14. Market Regime filter ──────────────────────────────────────
    # ในช่วง sideways (Hurst < 0.45) ลด confidence
    regime_ok = last['HURST'] > 0.45

    total = buy_sc + sell_sc
    if total == 0:
        return 'NEUTRAL', 0.5, 0, 0, [], regime_ok

    signal = 'BUY' if buy_sc >= sell_sc else 'SELL'
    ratio  = max(buy_sc, sell_sc) / total
    reasons = rb if signal == 'BUY' else rs

    return signal, ratio, buy_sc, sell_sc, reasons, regime_ok

print('✅ Scoring engine ready')

# ================== RISK MANAGEMENT ==================
def compute_risk(df, signal, conf):
    last  = df.iloc[-1]
    price = float(last['Close'])
    atr   = float(last['ATR'])

    # Dynamic multiplier: volatility regime ปรับ SL
    vol_r = float(last['VOL_REGIME'])  # 0=low, 1=normal, 2=high
    sl_mult = ATR_SL_MULT * (1 + vol_r * 0.1)
    tp_mult = ATR_TP_MULT * (1 + vol_r * 0.05)

    if signal == 'BUY':
        SL = price - sl_mult * atr
        TP = price + tp_mult * atr
    else:
        SL = price + sl_mult * atr
        TP = price - tp_mult * atr

    risk   = abs(price - SL)
    reward = abs(price - TP)
    rr     = reward / risk if risk > 0 else 0

    # Kelly Criterion
    kelly = max(0, min((rr * conf - (1 - conf)) / rr, 0.25)) * 100

    # ATR-based estimated hold time (1h bars)
    est_bars   = reward / atr
    est_hours  = est_bars  # เนื่องจาก medium TF = 1h

    return price, SL, TP, rr, kelly, atr, est_hours

print('✅ Risk management ready')

# ================== BACKTEST ==================
def backtest(df, n=100):
    d = df.copy().tail(n)
    d['sig'] = np.where(d['EMA9'] > d['EMA20'], 1, -1)
    d['ret'] = d['Close'].pct_change()
    d['sr']  = d['sig'].shift(1) * d['ret']
    d['cum'] = (1 + d['sr']).cumprod()
    tot_ret  = d['cum'].iloc[-1] - 1
    win_rate = (d['sr'] > 0).sum() / len(d)
    std      = d['sr'].std()
    sharpe   = d['sr'].mean() / std * np.sqrt(252 * 24) if std > 0 else 0
    dd       = (d['cum'] / d['cum'].cummax() - 1).min()
    profit_factor = d['sr'][d['sr']>0].sum() / abs(d['sr'][d['sr']<0].sum()) if (d['sr']<0).any() else 99
    return {
        'total_return':   tot_ret * 100,
        'win_rate':       win_rate * 100,
        'sharpe':         sharpe,
        'max_drawdown':   dd * 100,
        'profit_factor':  profit_factor,
        'total_trades':   int((d['sig'].diff() != 0).sum()),
    }

print('✅ Backtest ready')

# ================== SELF-LEARNING LOGGER ==================
def load_trade_log():
    if os.path.exists(TRADE_LOG_FILE):
        with open(TRADE_LOG_FILE) as f:
            return json.load(f)
    return []


def save_trade_log(log):
    with open(TRADE_LOG_FILE, 'w') as f:
        json.dump(log[-500:], f, indent=2)  # เก็บ 500 trades ล่าสุด


def log_signal(symbol, signal, conf, price, SL, TP):
    log = load_trade_log()
    log.append({
        'ts':      datetime.utcnow().isoformat(),
        'symbol':  symbol,
        'signal':  signal,
        'conf':    round(conf, 4),
        'price':   round(price, 6),
        'SL':      round(SL, 6),
        'TP':      round(TP, 6),
        'outcome': None,   # จะ update ทีหลัง
    })
    save_trade_log(log)


def get_self_learn_stats():
    """ดู win rate จาก history เพื่อ calibrate confidence"""
    log = [t for t in load_trade_log() if t.get('outcome') is not None]
    if not log:
        return {}
    total  = len(log)
    wins   = sum(1 for t in log if t['outcome'] == 'WIN')
    by_sym = defaultdict(lambda: {'wins': 0, 'total': 0})
    for t in log:
        by_sym[t['symbol']]['total'] += 1
        if t['outcome'] == 'WIN':
            by_sym[t['symbol']]['wins'] += 1
    return {
        'overall_win_rate': wins / total,
        'by_symbol':        dict(by_sym),
        'total_trades':     total,
    }

print('✅ Self-learning logger ready')

# ================== CHART (ULTRA) ==================
def plot_ultra(df, symbol, signal, SL, TP, price, conf, mtf_biases, bt):
    df_p = df.tail(150).copy()
    idx  = df_p.index
    clr  = '#00ff88' if signal == 'BUY' else '#ff4466'

    fig = plt.figure(figsize=(16, 12))
    fig.patch.set_facecolor('#090e1a')
    gs  = gridspec.GridSpec(5, 1, height_ratios=[5, 1.5, 1.5, 1.2, 1], hspace=0.06)
    axes = [fig.add_subplot(gs[i]) for i in range(5)]

    for ax in axes:
        ax.set_facecolor('#090e1a')
        ax.tick_params(colors='#556b8b', labelsize=7.5)
        for sp in ax.spines.values():
            sp.set_color('#1e2d45')

    ax1 = axes[0]
    # Ichimoku cloud
    ax1.fill_between(idx,
        df_p['ICHI_span_a'], df_p['ICHI_span_b'],
        where=df_p['ICHI_span_a'] >= df_p['ICHI_span_b'],
        alpha=0.12, color='#00ff88', label='Cloud+')
    ax1.fill_between(idx,
        df_p['ICHI_span_a'], df_p['ICHI_span_b'],
        where=df_p['ICHI_span_a'] <  df_p['ICHI_span_b'],
        alpha=0.12, color='#ff4466', label='Cloud-')

    # BB bands
    ax1.fill_between(idx, df_p['BB_high'], df_p['BB_low'],
                     alpha=0.06, color='#58a6ff')

    # EMA lines
    for ema, col, lw in [('EMA9','#ffd700',1.0),('EMA20','#58a6ff',0.9),
                          ('EMA50','#ff8c00',0.8),('EMA200','#cc44ff',0.7)]:
        ax1.plot(idx, df_p[ema], color=col, lw=lw, label=ema, alpha=0.85)

    ax1.plot(idx, df_p['VWAP'], color='#cc44ff', lw=0.8, ls=':', label='VWAP', alpha=0.7)
    ax1.plot(idx, df_p['Close'], color='#e0e8ff', lw=1.4, label='Price')

    # SL / TP lines
    ax1.axhline(SL, color='#ff4466', lw=1, ls='--', alpha=0.9)
    ax1.axhline(TP, color='#00ff88', lw=1, ls='--', alpha=0.9)
    ax1.scatter(idx[-1], price, color=clr, s=150, zorder=10)

    # SL/TP labels
    ax1.text(idx[-1], SL, f'  SL {SL:.5f}', color='#ff4466', fontsize=7, va='center')
    ax1.text(idx[-1], TP, f'  TP {TP:.5f}', color='#00ff88', fontsize=7, va='center')

    # MTF bias badges
    badge_x = 0.01
    for tf, info in mtf_biases.items():
        bc = '#00ff88' if info[0] == 'BUY' else ('#ff4466' if info[0] == 'SELL' else '#888')
        ax1.text(badge_x, 0.97, f'{tf.upper()} {info[0]}',
                 transform=ax1.transAxes, color=bc, fontsize=8, fontweight='bold',
                 va='top', bbox=dict(boxstyle='round,pad=0.3', fc='#0d1f3a', ec=bc, alpha=0.8))
        badge_x += 0.14

    ax1.set_title(
        f"{symbol}   {'🟢 BUY' if signal=='BUY' else '🔴 SELL'}   "
        f"Confidence: {conf*100:.1f}%   "
        f"WR: {bt['win_rate']:.0f}%  PF: {bt['profit_factor']:.2f}",
        color=clr, fontsize=12, fontweight='bold', pad=8)
    ax1.legend(loc='upper right', fontsize=7, facecolor='#0d1a2e',
               edgecolor='#1e2d45', labelcolor='#8fa0b8', ncol=4)
    ax1.set_xlim(idx[0], idx[-1])

    # RSI
    ax2 = axes[1]
    ax2.plot(idx, df_p['RSI'], color='#58a6ff', lw=1)
    ax2.plot(idx, df_p['RSI7'], color='#ffd700', lw=0.7, ls='--', alpha=0.7)
    ax2.axhline(70, color='#ff4466', lw=0.5, ls='--')
    ax2.axhline(30, color='#00ff88', lw=0.5, ls='--')
    ax2.fill_between(idx, df_p['RSI'], 70, where=df_p['RSI']>=70, alpha=0.15, color='#ff4466')
    ax2.fill_between(idx, df_p['RSI'], 30, where=df_p['RSI']<=30, alpha=0.15, color='#00ff88')
    ax2.set_ylabel('RSI', color='#556b8b', fontsize=8)
    ax2.set_ylim(0, 100); ax2.set_xlim(idx[0], idx[-1])

    # MACD
    ax3 = axes[2]
    ax3.plot(idx, df_p['MACD'], color='#58a6ff', lw=0.9)
    ax3.plot(idx, df_p['MACD_signal'], color='#ff8c00', lw=0.9)
    hist = df_p['MACD_hist']
    ax3.bar(idx, hist, color=np.where(hist >= 0, '#00ff88', '#ff4466'), alpha=0.6, width=0.02)
    ax3.axhline(0, color='#1e2d45', lw=0.5)
    ax3.set_ylabel('MACD', color='#556b8b', fontsize=8)
    ax3.set_xlim(idx[0], idx[-1])

    # Stochastic
    ax4 = axes[3]
    ax4.plot(idx, df_p['STOCH_k'], color='#00d4ff', lw=0.9, label='%K')
    ax4.plot(idx, df_p['STOCH_d'], color='#ff8c00', lw=0.9, label='%D', ls='--')
    ax4.axhline(80, color='#ff4466', lw=0.5, ls='--')
    ax4.axhline(20, color='#00ff88', lw=0.5, ls='--')
    ax4.fill_between(idx, df_p['STOCH_k'], 80, where=df_p['STOCH_k']>=80, alpha=0.1, color='#ff4466')
    ax4.fill_between(idx, df_p['STOCH_k'], 20, where=df_p['STOCH_k']<=20, alpha=0.1, color='#00ff88')
    ax4.set_ylabel('Stoch', color='#556b8b', fontsize=8)
    ax4.set_ylim(0, 100); ax4.set_xlim(idx[0], idx[-1])
    ax4.legend(loc='upper right', fontsize=7, facecolor='#0d1a2e',
               edgecolor='#1e2d45', labelcolor='#8fa0b8')

    # Volume
    ax5 = axes[4]
    if 'Volume' in df_p.columns:
        vc = ['#00ff88' if df_p['Close'].iloc[i] >= df_p['Open'].iloc[i]
              else '#ff4466' for i in range(len(df_p))]
        ax5.bar(idx, df_p['Volume'], color=vc, alpha=0.7, width=0.02)
        ax5.plot(idx, df_p['VOL_MA'], color='#ffd700', lw=0.8)
    ax5.set_ylabel('Vol', color='#556b8b', fontsize=8)
    ax5.set_xlim(idx[0], idx[-1])

    plt.tight_layout()
    fname = f"{symbol.replace('=','').replace('-','_').replace('^','')}_ultra.png"
    plt.savefig(fname, dpi=140, bbox_inches='tight', facecolor='#090e1a')
    plt.close()
    return fname

print('✅ Chart ready')

# ================== MAIN ANALYZE (FULL PIPELINE) ==================
def analyze(name, yf_symbol):
    print(f'  📊 {name} ({yf_symbol})...', end=' ')
    try:
        # ── Step 1: Fetch MTF data ────────────────────────────────
        mtf_data = fetch_mtf(yf_symbol)

        # ── Step 2: MTF bias ──────────────────────────────────────
        mtf_biases = mtf_bias(mtf_data)
        mtf_signal, mtf_conf, alignment = mtf_confluence_score(mtf_biases)

        # ── Step 3: Medium TF (main) ──────────────────────────────
        df_med = mtf_biases.get('medium', (None, None, None))[2]
        if df_med is None or len(df_med) < 100:
            print('⚠️ Not enough data')
            return None

        # ── Step 4: ADX filter (no signal in sideways) ─────────────
        adx_val = float(df_med['ADX'].iloc[-1])
        if adx_val < MIN_ADX:
            print(f'skip (ADX={adx_val:.0f} sideways)')
            return None

        # ── Step 5: ML ensemble ───────────────────────────────────
        model, scaler, ml_acc, ml_prec, feat_cols = train_ensemble(df_med)
        ml_p = ml_prob(model, scaler, df_med, feat_cols)

        # ── Step 6: Rule-based scoring ────────────────────────────
        rule_sig, rule_ratio, buy_sc, sell_sc, reasons, regime_ok = rule_score(df_med)

        # ── Step 7: Combine all signals ───────────────────────────
        ml_dir    = ml_p if rule_sig == 'BUY' else (1 - ml_p)
        mtf_dir   = mtf_conf if mtf_signal == rule_sig else (1 - mtf_conf)
        regime_mult = 1.0 if regime_ok else 0.85  # penalty for sideways

        final_conf = (
            0.40 * rule_ratio +
            0.30 * ml_dir     +
            0.30 * mtf_dir
        ) * regime_mult
        final_conf = min(0.98, final_conf)

        # Direction: majority vote
        votes = [rule_sig, mtf_signal,
                 ('BUY' if ml_p > 0.5 else 'SELL')]
        signal = max(set(votes), key=votes.count)

        if final_conf < MIN_CONF:
            print(f'skip (conf={final_conf:.2f})')
            return None

        # ── Step 8: Risk management ───────────────────────────────
        price, SL, TP, rr, kelly, atr, est_h = compute_risk(df_med, signal, final_conf)

        if rr < MIN_RR:
            print(f'skip (R:R={rr:.2f} too low)')
            return None

        # ── Step 9: Backtest ──────────────────────────────────────
        bt = backtest(df_med)

        # ── Step 10: Chart ────────────────────────────────────────
        chart = plot_ultra(df_med, name, signal, SL, TP,
                            price, final_conf, mtf_biases, bt)

        # ── Step 11: Log ──────────────────────────────────────────
        log_signal(name, signal, final_conf, price, SL, TP)

        emoji = '🟢' if signal == 'BUY' else '🔴'
        conf_lbl = (
            'VERY HIGH 🔥🔥' if final_conf > 0.82 else
            'HIGH 🔥'        if final_conf > 0.72 else
            'MEDIUM ⚠️'
        )
        mtf_str = '  '.join(
            f"{k.upper()}: {'🟢' if v[0]=='BUY' else '🔴'}"
            for k, v in mtf_biases.items()
        )
        reason_str = '\n'.join(f'  • {r}' for r in reasons[:6])

        msg = f"""{'='*45}
📊 {name}  ({yf_symbol})
{emoji} SIGNAL : {signal}  |  {conf_lbl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💰 Entry   : {price:.5f}
🛑 SL      : {SL:.5f}  (ATR×{ATR_SL_MULT})
🎯 TP      : {TP:.5f}  (ATR×{ATR_TP_MULT})
📐 R:R     : 1:{rr:.2f}
💼 Kelly   : {kelly:.1f}% of capital
⏱️ Est.Hold : {est_h:.0f} bars (~{est_h:.0f}h on 1H)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📈 Confidence  : {final_conf*100:.1f}%
   Rule-based  : {rule_ratio*100:.0f}%
   ML Ensemble : {ml_p*100:.0f}%  (Acc:{ml_acc*100:.0f}% Prec:{ml_prec*100:.0f}%)
   MTF Conf    : {mtf_conf*100:.0f}%  (Align: {alignment}/3)
📊 Score   : BUY={buy_sc:.1f}  SELL={sell_sc:.1f}  ADX={adx_val:.0f}
🌐 MTF     : {mtf_str}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Top Reasons:
{reason_str}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📉 Backtest (last 100 bars 1H):
  Return        : {bt['total_return']:.1f}%
  Win Rate      : {bt['win_rate']:.0f}%
  Sharpe Ratio  : {bt['sharpe']:.2f}
  Max Drawdown  : {bt['max_drawdown']:.1f}%
  Profit Factor : {bt['profit_factor']:.2f}
"""
        print(f'✅ {signal} conf={final_conf:.2f} RR={rr:.1f}')

        return {
            'name':    name,
            'symbol':  yf_symbol,
            'signal':  signal,
            'conf':    final_conf,
            'rr':      rr,
            'message': msg,
            'chart':   chart,
        }

    except Exception as e:
        import traceback
        print(f'❌ Error: {e}')
        traceback.print_exc()
        return None

print('✅ Main analyze ready')

# ================== EMAIL ==================
def send_email(subject, body, image_paths):
    try:
        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From']    = EMAIL
        msg['To']      = EMAIL
        msg.attach(MIMEText(body, 'plain', 'utf-8'))
        for p in image_paths:
            if os.path.exists(p):
                with open(p,'rb') as f:
                    img = MIMEImage(f.read())
                    img.add_header('Content-Disposition','attachment',
                                   filename=os.path.basename(p))
                    msg.attach(img)
        with smtplib.SMTP('smtp.gmail.com', 587) as sv:
            sv.starttls()
            sv.login(EMAIL, APP_PASSWORD)
            sv.send_message(msg)
        print(f'📧 Sent: {subject}')
    except Exception as e:
        print(f'❌ Email error: {e}')

print('✅ Email ready')

# ================== BOT RUNNER ==================
def run_bot():
    ts = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
    print(f'\n{"="*55}')
    print(f'🤖  AI TRADING BOT ULTRA  |  {ts}')
    print(f'{"="*55}')

    # แสดง self-learn stats ถ้ามี
    sl_stats = get_self_learn_stats()
    if sl_stats:
        print(f"📚 Historical WR: {sl_stats['overall_win_rate']*100:.0f}%  "
              f"({sl_stats['total_trades']} logged trades)")

    results = []
    for name, yf_sym in SYMBOLS.items():
        r = analyze(name, yf_sym)
        if r:
            results.append(r)
        time.sleep(1.2)

    if not results:
        print('\n❌ No qualifying signals this round')
        return

    # เรียงตาม conf × rr (quality score)
    results.sort(key=lambda x: x['conf'] * x['rr'], reverse=True)
    top = results[:TOP_N]

    full_msg = '\n\n'.join(r['message'] for r in top)
    charts   = [r['chart'] for r in top]
    names    = [r['name']  for r in top]

    subject = f"🔥 AI Signal TOP{TOP_N} [{ts}]: {', '.join(names)}"
    send_email(subject, full_msg, charts)

    print(f'\n✅ Sent TOP {TOP_N}: {names}')
    return results


# ── Run once ──────────────────────────────────────────────────────────
results = run_bot()

# ================== LOOP (รันต่อเนื่อง) ==================
#
# วิธีรันฟรีตลอด 24/7 บน Google Colab:
#
# 1) ใช้ JavaScript keep-alive ป้องกัน session หมดอายุ:
#    วาง code นี้ใน browser console:
#      setInterval(() => {document.querySelector("colab-connect-button").click()}, 60000)
#
# 2) หรือใช้ colab-xterm extension ให้ session อยู่ได้นานขึ้น
#
# 3) ฟรีที่สุด: GitHub Actions (รันทุกชั่วโมง ฟรี 2000 min/month)
#    — ดูคำแนะนำใน cell ถัดไป

# Uncomment เพื่อรัน loop:
# while True:
#     run_bot()
#     print(f'⏳ Next scan in 1 hour...')
#     time.sleep(3600)

"""## 🆓 วิธีรันฟรีตลอด 24/7

### ✅ ตัวเลือกที่ 1 — GitHub Actions (แนะนำที่สุด)
```
1. สร้าง repo ใหม่ใน GitHub
2. เพิ่มไฟล์ .github/workflows/bot.yml (ดู cell ถัดไป)
3. ใส่ secrets: TRADING_EMAIL, GMAIL_APP_PASSWORD
4. รันอัตโนมัติทุกชั่วโมง — ฟรี 2,000 นาที/เดือน
```

### ✅ ตัวเลือกที่ 2 — Google Colab + Keep-alive
```
1. เปิด Colab บน Chrome
2. กด F12 → Console → วาง:
   setInterval(() => {document.querySelector('colab-connect-button').click()}, 60000)
3. รัน while loop ใน notebook
4. ฟรีแต่ต้องเปิดหน้าต่างทิ้งไว้
```

### ✅ ตัวเลือกที่ 3 — Render.com / Railway.app
```
1. แปลง notebook เป็น bot.py
2. Deploy บน Render (free tier)
3. รันได้ 24/7 แบบ cloud จริงๆ
```
"""

# ================== GitHub Actions Workflow ==================
# สร้างไฟล์ .github/workflows/trading_bot.yml

github_actions_yml = '''
name: AI Trading Bot

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install yfinance pandas ta scikit-learn matplotlib numpy scipy

      - name: Run bot
        env:
          TRADING_EMAIL: ${{ secrets.TRADING_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python bot.py
'''

os.makedirs('.github/workflows', exist_ok=True)
with open('.github/workflows/trading_bot.yml', 'w') as f:
    f.write(github_actions_yml)

print('✅ GitHub Actions workflow saved!')
print('📂 File: .github/workflows/trading_bot.yml')
print()
print('📋 Next steps:')
print('  1. Push repo to GitHub')
print('  2. Settings → Secrets → New secret:')
print('     TRADING_EMAIL = your_email@gmail.com')
print('     GMAIL_APP_PASSWORD = xxxx xxxx xxxx xxxx')
print('  3. Bot จะรันอัตโนมัติทุกชั่วโมง 🎉')
